name: deplo0y

on:
  push:
    branches:
      - main


jobs:
  deploy:
    runs-on:
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        width:
          node-version: '14.x'
      - name: Build web-app
        run: |
          npm ci
          npm build
        - name: Deploy to gh-pages
          uses: peaceiris/actions-gh-pages@v3
          width
            github_token: ${{ secrects.GITHUB_TOKEN }}
            publish_dir: ./build